/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idea.test;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testFileExist() {
        System.out.printf("\n\nuser.dir: %s\n\n", System.getProperty("user.dir"));
        assertTrue(Files.exists(Paths.get("gradlew.bat")));
    }
}
